# Site settings
title: SAAR Services
email: eloy@saar.services
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://saar.services" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
